// js/embed.mjs — the JavaScript embedding entry point.
//
// Importing this module is the whole loading step: it injects the grammar
// data from js/embedded_grammar_data.mjs (generated by
// scripts/js_grammar_gen.py from grammar/vocabulary.json,
// grammar/messages/amber.json and grammar/core.json) into js/grammar_data.mjs
// as a synchronous, side-effect-free-to-repeat top-level statement — no `fs`
// read (js/loader_node.mjs's route, Node-only), no `fetch`, and no top-level
// `await` that would break a bundler expecting a synchronous module graph.
// That makes this module load unchanged under Node, in a browser tab (as
// js/browser_main.mjs already does with its own inlined copy), and in a
// Cloudflare Worker, which has neither `fs` nor a page to fetch from.
//
// Everything else this module exports is host-agnostic already — none of
// js/lexer.mjs, parser.mjs, shapes.mjs, rules.mjs, interp.mjs, host.mjs or
// planes_num.mjs import `node:fs` or anything else Node-only (grep the repo:
// only js/loader_node.mjs and js/module_loader_node.mjs do). This module is
// what makes that fact usable without also having to know it: a caller gets
// grammar data loaded and the main API in one `import`, and can never hit
// `GrammarDataError: vocabulary not loaded` (the finding 5xFive's VENDOR.md
// records against four review rounds) because there is no longer a window in
// which a caller could use the API before the load happens — the load IS the
// import.
//
// Exported names are the real ones from the modules that define them, not
// aliases: `parse` is js/parser.mjs's `parse`, `analyse` is js/shapes.mjs's
// `analyse`, `check` is js/rules.mjs's `check`, `Interpreter` is
// js/interp.mjs's `Interpreter`. See js/embed.d.mts for documented types, and
// js/cli.mjs for the fuller catalogue this is drawn from (every export below
// is something `js/cli.mjs` itself calls, minus the Node-only file-following
// and multi-file module-graph paths, which need `fs` and stay out of this
// module on purpose — a host that wants those can import js/modules.mjs and
// js/module_loader_node.mjs directly, the same way js/cli.mjs does).

import { vocabulary, amber, core } from "./embedded_grammar_data.mjs";
import { setVocabulary, setAmberTemplates, setCore, GrammarDataError } from "./grammar_data.mjs";

setVocabulary(vocabulary);
setAmberTemplates(amber);
setCore(core);

// ---- lexing (js/lexer.mjs)
export { tokenize, keywords, effectKinds, builtinNames, PlanesSyntaxError } from "./lexer.mjs";

// ---- parsing (js/parser.mjs)
export { parse, PlanesAmbiguity } from "./parser.mjs";

// ---- effect-surface analysis (js/shapes.mjs) — "analyse" in the item's own
// spelling; asJson/functionsBreakdown/derivationForm/diff are the surface-JSON
// rendering and diff forms js/cli.mjs's `shapes`/`shapes-fn`/`shapes-deriv`
// subcommands and shapes_cli.py's `--diff` publish.
export {
  analyse,
  asJson,
  functionsBreakdown,
  derivationForm,
  diff,
  SurfaceDiff,
  FORMAT_VERSION as SURFACE_FORMAT_VERSION,
} from "./shapes.mjs";

// ---- rule checking (js/rules.mjs)
export { check, fingerprint, condition, RuleConflict, RuleNotSupported } from "./rules.mjs";

// ---- running programs (js/interp.mjs). `Traced`/`lit` are the wrapper
// `Interpreter#env.get(name)` returns and the way to build one from a plain
// host value, respectively — see js/embed.d.mts for the value-crossing shapes.
export {
  Interpreter,
  PlanesError,
  CoreRestrictionError,
  Traced,
  lit,
  fmt,
  toJson,
  toHost,
  fromForeign,
} from "./interp.mjs";

// ---- hosts (js/host.mjs) — Host is the abstract base a real embedding host
// implements; MemoryHost/TestHost are the in-memory stand-ins js/cli.mjs's own
// `run`/`run-batch`/`meta` use, ready to use as-is for a program that does not
// need a real filesystem or network.
export { Host, HostError, MemoryHost, TestHost } from "./host.mjs";

// ---- exact-rational numbers (js/planes_num.mjs) — see js/embed.d.mts for how
// a Planes number is represented (a Fraction of two BigInts, never a float).
export { PlanesNumber, Fraction, Inexact, NotANumber, numberFromText } from "./planes_num.mjs";

// ---- the grammar-data error class itself, for a `catch` that wants to name
// it. Never thrown by anything in this module — the load above always
// succeeds or throws synchronously during import — but exported because
// js/interp.mjs, js/lexer.mjs and others still declare it in their own
// surfaces and a host may want `instanceof GrammarDataError` for symmetry.
export { GrammarDataError };
