#!/usr/bin/env python3
"""corpus_coverage — measure what the canonical corpus exercises.

Reports, over a set of .planes files (`corpus/` by default):

  * which of the 32 reserved words appear,
  * which of the 10 builtins appear,
  * which of the 7 effect kinds appear,
  * which grammar-derived compositions appear.

Every list is DERIVED, never hand-written (S7, A.2). Reserved words come from
`lexer.KEYWORDS`, builtins from `parser.BUILTIN_NAMES`, and effect kinds from
`lexer.EFFECT_KINDS` -- all three of which load `grammar/vocabulary.json`, the
single source of truth. The composition universe is generated by nesting every
expression kind inside every container position, the matrix technique the
render-composition build (#24, test_render_composition.py) established; the
container templates and inner fragments below are that same matrix, kept here so
the checker and that test speak one composition vocabulary. A corpus program's
compositions are read straight off its parsed AST -- every parent->child node
adjacency -- so "which compositions appear" is a fact about the tree, not a
guess.

It REPORTS gaps; it never fails on them (A.2, S7 invariant 7). A construct absent
from the corpus may simply be one no real program would reach for, and forcing
one into existence to satisfy a checker produces exactly the fixture-shaped file
the corpus is defined to exclude. This is a CI *report*, not a gate: it always
exits 0.

  python3 corpus_coverage.py                 # coverage over corpus/
  python3 corpus_coverage.py demo *.planes   # a baseline over other files
  python3 corpus_coverage.py --json          # machine-readable
"""
import dataclasses
import glob
import json
import os
import sys

from lexer import EFFECT_KINDS, KEYWORDS, PlanesSyntaxError, tokenize
from parser import BUILTIN_NAMES, parse
from shapes import analyse

# ---------------------------------------------------------------- the composition matrix
#
# The same container x inner matrix the render-composition build (#24) uses to
# prove render round-trips every nesting (test_render_composition.py). Reused
# here -- not re-derived -- so the two agree on what a "composition" is. INNER
# lists every expression kind the parser can produce as a sub-expression;
# CONTAINER lists every grammar position that reads one, with HOLE marking the
# slot. The universe of compositions is every (container, inner) pair that
# parses; the corpus's coverage is which of those pairs its programs contain.

_PRELUDE = (
    "to f of a, b:\n  give a\n\n"
    "to g of a:\n  give a\n\n"
    "to cc of a, b:\n  give a\n\n"
)

_INNER = {
    "Num": "1",
    "Str": '"s"',
    "Bool": "true",
    "Nothing": "nothing",
    "Var": "z",
    "ListLit": "[1, 2]",
    "RecordLit": "{ a: 1 }",
    "RecordUpdate": "(p with a: 1, b: 2)",
    "ListPlus": "(xs plus 1)",
    "BinOpAdd": "(1 + 2)",
    "BinOpCmp": "(z > 0)",
    "First": "(first (k) of parts)",
    "Not": "(not z)",
    "IsNothing": "(z is nothing)",
    "Field": "z.fld",
    "Call2": "(f of a, b)",
    "Call1": "(g of a)",
    "Round": "(round v to 2 places)",
    "ForEach": "(for each i in xs: i)",
    "OrFail": "(g of a or fail as e)",
}

_CONTAINER = {
    "record-field-first": "x = { k: HOLE, k2: 9 }\n",
    "record-field-last": "x = { k1: 9, k: HOLE }\n",
    "record-field-only": "x = { k: HOLE }\n",
    "recordupdate-field-first": "x = p with k: HOLE, k2: 9\n",
    "recordupdate-field-last": "x = p with k1: 9, k: HOLE\n",
    "list-first": "x = [HOLE, 9]\n",
    "list-last": "x = [9, HOLE]\n",
    "list-only": "x = [HOLE]\n",
    "call-arg-first": "x = cc of (HOLE), (9)\n",
    "call-arg-last": "x = cc of (9), (HOLE)\n",
    "field-base": "x = (HOLE).fld\n",
    "binop-left": "x = HOLE + 1\n",
    "binop-right": "x = 1 + HOLE\n",
    "not-operand": "x = not HOLE\n",
    "isnothing-operand": "x = HOLE is nothing\n",
    "round-value": "x = round HOLE to 2 places\n",
    "round-places": "x = round v to HOLE places\n",
    "listplus-base": "x = HOLE plus 1\n",
    "listplus-item": "x = xs plus HOLE\n",
    "assign-rhs": "x = HOLE\n",
    "give": "to fn:\n  give HOLE\n",
    "show": "show HOLE\n",
    "if-cond": "if HOLE:\n  show 1\n",
    "foreach-source": "x = for each i in HOLE: i\n",
    "foreach-where": "x = for each i in xs where HOLE: i\n",
    "foreach-body": "x = for each i in xs: HOLE\n",
    "when-subject": "when HOLE is { a: 1 }:\n  show 1\n",
    "when-match": "when r is { a: HOLE }:\n  show 1\n",
    "writeto-value": 'write HOLE to "f"\n',
    "writeto-dest": 'write [1] to HOLE\n',
    "orfail-expr": "x = HOLE or fail as e\n",
    "first-count": "x = first (HOLE) of parts\n",
    "first-list": "x = first (k) of (HOLE)\n",
    "fail-message": "fail HOLE as t\n",
}


def _is_node(v):
    return dataclasses.is_dataclass(v) and not isinstance(v, type)


def composition_pairs(prog):
    """Every parent->child AST adjacency in a program, as a set of
    (parent-kind, field, child-kind) triples. This is what a "composition" is:
    one node kind sitting in a named slot of another. Read straight off the
    tree, so it reflects the program exactly."""
    pairs = set()

    def children_of(node):
        """(field-name, child-node) for every AST node directly under `node`,
        reaching through lists and (name, expr)-style tuples."""
        for f in dataclasses.fields(node):
            val = getattr(node, f.name)
            for child in _reach(val):
                yield f.name, child

    def _reach(val):
        if _is_node(val):
            yield val
        elif isinstance(val, (list, tuple)):
            for item in val:
                yield from _reach(item)

    def walk(node):
        for field, child in children_of(node):
            pairs.add((type(node).__name__, field, type(child).__name__))
            walk(child)

    for stmt in prog:
        walk(stmt)
    return pairs


_UNIVERSE = None


def composition_universe():
    """The set of (parent, field, child) triples the #24 matrix exercises --
    every expression kind nested in every container position that parses. The
    grammar-derived denominator for composition coverage. Cached."""
    global _UNIVERSE
    if _UNIVERSE is not None:
        return _UNIVERSE
    universe = set()
    for template in _CONTAINER.values():
        for fragment in _INNER.values():
            src = _PRELUDE + template.replace("HOLE", fragment)
            try:
                prog = parse(src)
            except PlanesSyntaxError:
                continue                       # a nesting the grammar rejects
            universe |= composition_pairs(prog)
    _UNIVERSE = universe
    return universe


# ---------------------------------------------------------------- the four dimensions

def reserved_words_in(src):
    """Which reserved words the source tokenizes to. The lexer upcases a NAME
    whose text is a keyword (`to` -> TO), so a keyword token is exactly one
    whose kind is its own value upper-cased."""
    words = set()
    for t in tokenize(src):
        if t.value in KEYWORDS and t.kind == t.value.upper():
            words.add(t.value)
    return words


def builtins_in(prog):
    """Which builtins are actually called. A builtin is a Call by one of the
    ten builtin names; a user function of the same name shadows it
    (test_names.py's test_user_definition_shadows_a_builtin), so a
    locally-defined name is not counted as the builtin."""
    defined = {s.name for s in prog if type(s).__name__ == "FuncDef"}
    found = set()

    def walk(node):
        if type(node).__name__ == "Call" and node.name in BUILTIN_NAMES \
                and node.name not in defined:
            found.add(node.name)
        if _is_node(node):
            for f in dataclasses.fields(node):
                _walkval(getattr(node, f.name))

    def _walkval(val):
        if _is_node(val):
            walk(val)
        elif isinstance(val, (list, tuple)):
            for item in val:
                _walkval(item)

    for stmt in prog:
        walk(stmt)
    return found


def effect_kinds_in(src):
    """Which of the seven effect kinds the file's declared surface touches --
    from shapes.analyse, the same static surface `shapes_cli.py` publishes."""
    surface = analyse(src)
    return set(surface.kinds())


# ---------------------------------------------------------------- aggregation & report

def _corpus_files(paths):
    files = []
    for pat in paths:
        if os.path.isdir(pat):
            files.extend(sorted(glob.glob(os.path.join(pat, "**", "*.planes"),
                                          recursive=True)))
        else:
            files.extend(sorted(glob.glob(pat)))
    # de-dup, keep order
    return list(dict.fromkeys(files))


def coverage(paths):
    """Aggregate coverage across `paths`. Returns a dict with the four
    dimensions, the per-dimension universe, and any files that would not
    parse (reported, never fatal)."""
    files = _corpus_files(paths)
    words, builtins, kinds, comps = set(), set(), set(), set()
    unparseable = []
    analysed = 0
    for f in files:
        src = open(f, encoding="utf-8").read()
        try:
            prog = parse(src)
        except PlanesSyntaxError as e:
            unparseable.append((f, str(e).splitlines()[0]))
            continue
        words |= reserved_words_in(src)
        builtins |= builtins_in(prog)
        try:
            kinds |= effect_kinds_in(src)
        except Exception:  # noqa: BLE001  -- a surface that cannot be computed
            pass           #    is a reported blank, never a crash of the report
        comps |= composition_pairs(prog)
        analysed += 1

    universe = composition_universe()
    return {
        "files": files,
        "analysed": analysed,
        "unparseable": unparseable,
        "reserved_words": {
            "present": sorted(words),
            "absent": sorted(KEYWORDS - words),
            "total": len(KEYWORDS),
        },
        "builtins": {
            "present": sorted(builtins),
            "absent": sorted(BUILTIN_NAMES - builtins),
            "total": len(BUILTIN_NAMES),
        },
        "effect_kinds": {
            "present": sorted(kinds),
            "absent": sorted(set(EFFECT_KINDS) - kinds),
            "total": len(EFFECT_KINDS),
        },
        "compositions": {
            "present": len(comps & universe),
            "absent": sorted(f"{p}.{f} <- {c}" for (p, f, c) in universe - comps),
            "total": len(universe),
            "beyond_matrix": len(comps - universe),
        },
    }


def _bar(present, total):
    return f"{present}/{total}"


def render_report(cov):
    lines = []
    lines.append(f"corpus coverage — {cov['analysed']} file(s)"
                 + (f", {len(cov['unparseable'])} unparseable"
                    if cov["unparseable"] else ""))
    lines.append("")

    rw = cov["reserved_words"]
    lines.append(f"reserved words   {_bar(len(rw['present']), rw['total'])}")
    if rw["absent"]:
        lines.append(f"  absent: {', '.join(rw['absent'])}")

    bi = cov["builtins"]
    lines.append(f"builtins         {_bar(len(bi['present']), bi['total'])}")
    if bi["absent"]:
        lines.append(f"  absent: {', '.join(bi['absent'])}")

    ek = cov["effect_kinds"]
    lines.append(f"effect kinds     {_bar(len(ek['present']), ek['total'])}")
    if ek["absent"]:
        lines.append(f"  absent: {', '.join(ek['absent'])}")

    co = cov["compositions"]
    lines.append(f"compositions     {_bar(co['present'], co['total'])}"
                 f"  (+{co['beyond_matrix']} beyond the #24 matrix)")
    if co["absent"]:
        lines.append(f"  {len(co['absent'])} matrix composition(s) not in the "
                     f"corpus, e.g.:")
        for a in co["absent"][:12]:
            lines.append(f"    {a}")
        if len(co["absent"]) > 12:
            lines.append(f"    ... and {len(co['absent']) - 12} more")

    if cov["unparseable"]:
        lines.append("")
        lines.append("did not parse (reported, not a failure):")
        for f, msg in cov["unparseable"]:
            lines.append(f"  {f}: {msg}")

    lines.append("")
    lines.append("gaps are reported, not required: a construct no real program "
                 "would use is a deliberate gap, not a hole to plug.")
    return "\n".join(lines)


def main(argv):
    args = argv[1:]
    as_json = "--json" in args
    if as_json:
        args.remove("--json")
    paths = args or ["corpus"]
    cov = coverage(paths)
    if as_json:
        # Drop the file list's absolute noise; keep the counts and the gaps.
        out = {k: v for k, v in cov.items() if k != "files"}
        print(json.dumps(out, indent=2))
    else:
        print(render_report(cov))
    return 0        # a report never fails (A.2)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
