#!/usr/bin/env python3
"""errors_coverage — does every catalogued error name its fix?

`errors name the fix` has been a language-level commitment since unbound v1.1
§22 — the highest-leverage machine-authorship affordance in Planes, because a
message that reports a token mismatch without saying what to write instead
leaves an author (human or machine) with a true statement and no next move.
S8 counted it for the first time. C2 closed the shortfall and gave the
measurement a floor.

WHAT IS MEASURED — the inclusion rule, stated (C2, A.2 item 2)

The catalogue is `grammar/errors.json`, generated by `grammar_gen.py` from the
raise sites themselves, so this measures the code and not a hand-kept list.
Each entry carries a `kind`, and the rule for it lives in `grammar_gen.py`
beside the class list it governs:

  error    the entry constructs one of the seven error classes the reference
           implementation defines. Measured here.
  report   the entry is text a plane renders for a person without raising —
           rules.py's `Violation.render` and `_render_vacuous`. Counted and
           listed, never measured: an error stops a program and leaves its
           author needing a next move, and a report does not.

Four report lines used to be counted as passes, which inflated the 70 S8
measured. They are not errors, and the number that matters is the one that is
a work list.

THREE STATES, AND WHY NOT A PERCENTAGE (C2, A.3)

  names a fix                  the entry carries a `fix` field (the third
                               constructor argument), or its message template
                               runs to more than one line — the continuation
                               clause every fix-naming message in this repo
                               uses. A site that delegates to
                               grammar/messages/amber.json counts here only if
                               every template it delegates to carries its own
                               `fix`; the delegating share is reported
                               separately so the dependency stays visible.
  deliberately names none      the raise site states, in words, why it names
                               none — the `no_fix` argument, read as a literal
                               at the site exactly as the message is. Two
                               shapes qualify: a message the language did not
                               write (`fail`'s own text, an `or fail` re-tag),
                               and a gate too generic to know what the author
                               meant (`expect`). Marked, never silent.
  should name one and does not the work list. Its target is zero — not that
                               the first state reaches 100%, which it cannot
                               once deliberate silences exist and would be
                               the wrong thing to chase if it could.

An entry whose message is not a literal at the raise site is *unreadable* to
this checker. That is not a state of its own: unreadable-with-a-stated-reason
is a decision, and unreadable-without-one is shortfall. It is reported as a
figure so it stays visible, and it is never counted as a pass.

It REPORTS; it never fails. A message with no fix clause is a fact to weigh
and schedule, not a build break — and gating CI on it would mean the first
person to add an honest one-line error has to write prose before they can
commit. Same contract as corpus_coverage.py: this always exits 0.

  python3 errors_coverage.py            # the report
  python3 errors_coverage.py --json     # machine-readable
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
ERRORS_PATH = os.path.join(REPO, "grammar", "errors.json")
AMBER_PATH = os.path.join(REPO, "grammar", "messages", "amber.json")

# The shape every fix-naming message in this repo uses: the detail line, then a
# continuation clause on its own line. `check_binding_name`'s builtin-collision
# message is the reference instance. The test is "more than one line" rather
# than the exact two-space indent, because a message composed across branches
# (rules.py's vacuous-rule reports) is catalogued as its raw pieces and the
# indent the renderer adds is not part of the template.
FIX_CONTINUATION = "\n"

NAMES_FIX = "names a fix"
DELIBERATE = "deliberately names none"
SHORTFALL = "should name one and does not"

STATES = (NAMES_FIX, DELIBERATE, SHORTFALL)

ERROR_KIND = "error"
REPORT_KIND = "report"


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def amber_templates_all_name_a_fix(amber):
    """Whether every amber template carries its own `fix`. A delegation is
    only as good as what it delegates to."""
    templates = amber.get("templates", [])
    return bool(templates) and all(t.get("fix") for t in templates)


def delegates(entry):
    return "amber.json" in (entry.get("note") or "")


def classify(entry, amber_ok):
    """One of the three states. Order matters: a site that names a fix names
    one whether or not it also carries a `no_fix` reason, and a stated reason
    only settles a site that names none."""
    if entry.get("fix"):
        return NAMES_FIX
    template = entry.get("template")
    if template and FIX_CONTINUATION in template:
        return NAMES_FIX
    if delegates(entry):
        return NAMES_FIX if amber_ok else SHORTFALL
    if entry.get("no_fix"):
        return DELIBERATE
    return SHORTFALL


def is_unreadable(entry):
    """The message is not a literal at the raise site, so this checker cannot
    read whether it names a fix. A figure, not a state — see the module
    docstring."""
    if entry.get("fix") or delegates(entry):
        return False
    return entry.get("template") is None


def coverage():
    cat = load(ERRORS_PATH)
    amber_ok = amber_templates_all_name_a_fix(load(AMBER_PATH))
    errors = [e for e in cat["entries"]
              if e.get("kind", ERROR_KIND) == ERROR_KIND]
    reports = [e for e in cat["entries"] if e.get("kind") == REPORT_KIND]

    buckets = {s: [] for s in STATES}
    for e in errors:
        buckets[classify(e, amber_ok)].append(e)

    def brief(e, *extra):
        out = {"id": e["id"], "source": e["source"], "class": e["class"]}
        for k in extra:
            out[k] = e.get(k)
        return out

    return {
        "total": len(cat["entries"]),
        "errors": len(errors),
        "reports": [brief(e) for e in reports],
        "amber_templates_all_name_a_fix": amber_ok,
        "delegating": sum(1 for e in errors if delegates(e)),
        "counts": {s: len(buckets[s]) for s in STATES},
        "work_list": [brief(e, "template") | {"unreadable": is_unreadable(e)}
                      for e in buckets[SHORTFALL]],
        "deliberate": [brief(e, "no_fix") for e in buckets[DELIBERATE]],
        "unreadable": [brief(e) for e in errors if is_unreadable(e)],
    }


def render_report(cov):
    lines = []
    lines.append("errors_coverage: grammar/errors.json against "
                 "`errors name the fix`")
    lines.append("=" * 72)
    lines.append("")
    lines.append(f"  {cov['total']} catalogued message sites: "
                 f"{cov['errors']} errors, {len(cov['reports'])} rule-plane "
                 f"reports.")
    lines.append("  An entry is an error iff it constructs one of the seven "
                 "error classes the")
    lines.append("  reference defines (the rule, with its exclusions, is in "
                 "grammar_gen.py). A")
    lines.append("  report is text a plane renders without raising; it is "
                 "listed, not measured.")
    lines.append("")
    total = cov["errors"]
    c = cov["counts"]
    for label in STATES:
        n = c[label]
        pct = f"{100 * n / total:.0f}%" if total else "-"
        lines.append(f"  {label:<28} {n:>3} of {total}  ({pct})")
    lines.append("")
    lines.append(f"  THE WORK LIST: {c[SHORTFALL]}. Its target is zero.")
    lines.append(f"  Of the {c[NAMES_FIX]} that name one, {cov['delegating']} "
                 f"delegate to grammar/messages/amber.json,")
    lines.append("  which counts only because every template there carries "
                 "its own fix.")
    lines.append(f"  Unreadable at the raise site: {len(cov['unreadable'])} "
                 f"— never counted as a pass.")
    lines.append("")

    if not cov["amber_templates_all_name_a_fix"]:
        lines.append("  WARNING: an amber template carries no `fix` field; "
                     "delegating sites counted as naming none.")
        lines.append("")

    if cov["work_list"]:
        lines.append(f"SHOULD NAME ONE AND DOES NOT ({len(cov['work_list'])}) "
                     "— the work list, reported not enforced.")
        lines.append("Measured structurally: a message that names its fix "
                     "inline in prose is counted")
        lines.append("here too, because a catalogue needs the fix in a field "
                     "or on its own line.")
        for e in cov["work_list"]:
            mark = "  (unreadable here)" if e["unreadable"] else ""
            lines.append(f"  {e['source']:<22} {e['id']}{mark}")
            if e["template"]:
                lines.append(f"      {e['template']}")
        lines.append("")

    if cov["deliberate"]:
        lines.append(f"DELIBERATELY NAMES NONE ({len(cov['deliberate'])}) — "
                     "each with the reason its raise site states.")
        lines.append("Not a gap and not a pass: a distinct decision, so the "
                     "work list above stays")
        lines.append("a work list as it approaches its floor.")
        for e in cov["deliberate"]:
            lines.append(f"  {e['source']:<22} {e['id']}")
            lines.append(f"      {e['no_fix']}")
        lines.append("")

    if cov["reports"]:
        lines.append(f"rule-plane reports ({len(cov['reports'])}) — "
                     "catalogued as text a person reads, and not")
        lines.append("measured against a commitment about errors:")
        for e in cov["reports"]:
            lines.append(f"  {e['source']:<22} {e['id']}")
        lines.append("")

    lines.append("This is a report, never a gate. A message with no fix clause "
                 "is work to schedule,")
    lines.append("not a build to break — and an honest one-line error should "
                 "not be un-committable.")
    return "\n".join(lines)


def main(argv):
    args = argv[1:]
    cov = coverage()
    if "--json" in args:
        print(json.dumps(cov, indent=2))
    else:
        print(render_report(cov))
    return 0        # a report never fails


if __name__ == "__main__":
    sys.exit(main(sys.argv))
