#!/usr/bin/env python3
"""errors_coverage — does every catalogued error name its fix?

`errors name the fix` has been a language-level commitment since unbound v1.1
§22 — the highest-leverage machine-authorship affordance in Planes, because a
message that reports a token mismatch without saying what to write instead
leaves an author (human or machine) with a true statement and no next move.
The commitment has been asserted for many builds and never counted. This
counts it.

The catalogue is `grammar/errors.json`, generated by `grammar_gen.py` from the
raise sites themselves — so this measures the code, not a hand-kept list. Each
entry is placed in one of four buckets:

  names a fix    the entry carries a `fix` field (PlanesError's third
                 argument), or its message template runs to more than one
                 line — the continuation clause every fix-naming message in
                 this repo uses. (More than one line, not `\\n  ` exactly:
                 a message composed across branches is catalogued as its raw
                 pieces, so the two-space indent the renderer adds is not in
                 the template.)
  delegates      the message is composed from grammar/messages/amber.json;
                 the delegated templates are read and their own `fix` fields
                 checked, so a delegation is only counted as naming a fix if
                 the template it delegates to actually does;
  unreadable     the message is assembled away from the raise site, so the
                 generator could not capture it and this checker cannot see
                 whether it names a fix. Never counted as a pass — an
                 unknown is reported as an unknown;
  NAMES NO FIX   the message is readable and carries no fix clause the
                 catalogue can see. This is the shortfall. It is measured
                 structurally on purpose: a message that names its fix inline
                 in prose ("... -- the four recognized escapes are ...") is
                 counted here, because a catalogue an author or a tool reads
                 needs the fix in a field or on its own line, not buried in a
                 sentence. So the shortfall doubles as the work list for
                 making those fixes structural.

It REPORTS; it never fails. A message with no fix clause is a fact to weigh
and schedule, not a build break — and gating CI on it would mean the first
person to add an honest one-line error has to write prose before they can
commit. Same contract as corpus_coverage.py: this always exits 0.

  python3 errors_coverage.py            # the report
  python3 errors_coverage.py --json     # machine-readable
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
ERRORS_PATH = os.path.join(REPO, "grammar", "errors.json")
AMBER_PATH = os.path.join(REPO, "grammar", "messages", "amber.json")

# The shape every fix-naming message in this repo uses: the detail line, then a
# continuation clause on its own line. `check_binding_name`'s builtin-collision
# message is the reference instance. The test is "more than one line" rather
# than the exact two-space indent, because a message composed across branches
# (rules.py's vacuous-rule reports) is catalogued as its raw pieces and the
# indent the renderer adds is not part of the template.
FIX_CONTINUATION = "\n"

NAMES_FIX = "names a fix"
DELEGATES = "delegates"
UNREADABLE = "unreadable"
NO_FIX = "NAMES NO FIX"


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def amber_templates_all_name_a_fix(amber):
    """Whether every amber template carries its own `fix`. A delegation is
    only as good as what it delegates to."""
    templates = amber.get("templates", [])
    return bool(templates) and all(t.get("fix") for t in templates)


def classify(entry, amber_ok):
    if entry.get("fix"):
        return NAMES_FIX
    template = entry.get("template")
    if template and FIX_CONTINUATION in template:
        return NAMES_FIX
    note = entry.get("note") or ""
    if "amber.json" in note:
        return DELEGATES if amber_ok else NO_FIX
    if template is None:
        return UNREADABLE
    return NO_FIX


def coverage():
    cat = load(ERRORS_PATH)
    amber_ok = amber_templates_all_name_a_fix(load(AMBER_PATH))
    buckets = {NAMES_FIX: [], DELEGATES: [], UNREADABLE: [], NO_FIX: []}
    for e in cat["entries"]:
        buckets[classify(e, amber_ok)].append(e)
    return {
        "total": len(cat["entries"]),
        "amber_templates_all_name_a_fix": amber_ok,
        "counts": {k: len(v) for k, v in buckets.items()},
        "shortfall": [
            {"id": e["id"], "source": e["source"], "class": e["class"],
             "template": e.get("template")}
            for e in buckets[NO_FIX]
        ],
        "unreadable": [
            {"id": e["id"], "source": e["source"], "class": e["class"]}
            for e in buckets[UNREADABLE]
        ],
    }


def render_report(cov):
    lines = []
    lines.append("errors_coverage: grammar/errors.json against "
                 "`errors name the fix`")
    lines.append("=" * 72)
    lines.append("")
    total = cov["total"]
    c = cov["counts"]
    for label in (NAMES_FIX, DELEGATES, UNREADABLE, NO_FIX):
        n = c[label]
        pct = f"{100 * n / total:.0f}%" if total else "-"
        lines.append(f"  {label:<14} {n:>3} of {total}  ({pct})")
    lines.append("")
    if not cov["amber_templates_all_name_a_fix"]:
        lines.append("  WARNING: an amber template carries no `fix` field; "
                     "delegating sites counted as naming none.")
        lines.append("")

    if cov["shortfall"]:
        lines.append(f"NAMES NO FIX ({len(cov['shortfall'])}) — the shortfall, "
                     "reported not enforced.")
        lines.append("Measured structurally: a message that names its fix "
                     "inline in prose is counted")
        lines.append("here too, because a catalogue needs the fix in a field "
                     "or on its own line.")
        for e in cov["shortfall"]:
            lines.append(f"  {e['source']:<22} {e['id']}")
            if e["template"]:
                lines.append(f"      {e['template']}")
        lines.append("")

    if cov["unreadable"]:
        lines.append(f"unreadable ({len(cov['unreadable'])}) — the message is "
                     "assembled away from the raise site, so whether it names "
                     "a fix cannot be read here:")
        for e in cov["unreadable"]:
            lines.append(f"  {e['source']:<22} {e['id']}")
        lines.append("")

    lines.append("This is a report, never a gate. A message with no fix clause "
                 "is work to schedule,")
    lines.append("not a build to break — and an honest one-line error should "
                 "not be un-committable.")
    return "\n".join(lines)


def main(argv):
    args = argv[1:]
    cov = coverage()
    if "--json" in args:
        print(json.dumps(cov, indent=2))
    else:
        print(render_report(cov))
    return 0        # a report never fails


if __name__ == "__main__":
    sys.exit(main(sys.argv))
