// js/test/embedded_grammar_data.test.mjs — the generated embedding held to a
// fresh disk read.
//
// js/embedded_grammar_data.mjs (generated by scripts/js_grammar_gen.py) is a
// second route to the same three files js/loader_node.mjs reads with `fs`.
// scripts/js_grammar_gen.py's own `--check` (test_js_grammar_data.py) proves
// the generated SOURCE TEXT is current; this proves the two loading routes
// produce the IDENTICAL parsed data by actually loading both and comparing —
// the fact js/embed.mjs's correctness depends on.
//
// Run: node --test js/test/

import { test } from "node:test";
import assert from "node:assert/strict";
import * as embedded from "../embedded_grammar_data.mjs";
import { loadGrammar } from "../loader_node.mjs";
import { vocabulary, amberTemplates, core } from "../grammar_data.mjs";

test("the embedded vocabulary/amber/core match a fresh disk read, field for field", () => {
  loadGrammar();
  assert.deepEqual(embedded.vocabulary, vocabulary());
  const embeddedAmberById = {};
  for (const t of embedded.amber.templates) embeddedAmberById[t.id] = t;
  assert.deepEqual(embeddedAmberById, amberTemplates());
  assert.deepEqual(embedded.core, core());
});

test("importing the generated module alone has no side effect on grammar_data.mjs", async () => {
  // A fresh module instance (Node's ESM cache is per-resolved-specifier, so a
  // cache-busting query string forces re-evaluation) that imports ONLY
  // embedded_grammar_data.mjs and grammar_data.mjs, never embed.mjs or
  // loader_node.mjs, must still see the grammar as unloaded.
  const gd = await import(`../grammar_data.mjs?embedded-data-side-effect-check`);
  await import(`../embedded_grammar_data.mjs?embedded-data-side-effect-check`);
  assert.equal(gd.vocabularyLoaded(), false);
  assert.equal(gd.coreLoaded(), false);
});
