#!/usr/bin/env python3
"""Embed the grammar's JSON data in the JavaScript implementation, for a host
that cannot read a file off disk.

    python3 scripts/js_grammar_gen.py            write the JS module
    python3 scripts/js_grammar_gen.py --check    regenerate into memory, diff
                                                  against the committed file,
                                                  exit non-zero on any difference

js/loader_node.mjs reads grammar/vocabulary.json, grammar/messages/amber.json
and grammar/core.json off disk with `fs` and injects them into
js/grammar_data.mjs -- fine for a Node CLI, but no use to a browser tab, a
Cloudflare Worker, or any other host that embeds the JavaScript implementation
as a library rather than checking out this repo. So the same three files are
embedded verbatim, as JSON text inside template-literal strings, in
js/embedded_grammar_data.mjs, and JSON.parse'd once at import. js/embed.mjs is
what actually injects the result into js/grammar_data.mjs; importing the
generated module alone has no side effect, exactly like an unloaded
grammar_data.mjs today.

(js/browser_main.mjs takes a different route to the same data: it imports the
JSON files directly with `with { type: "json" }`. That needs a browser or a
bundler that understands JSON module imports, and Node's own support for it is
recent enough that a Cloudflare Worker cannot be assumed to have it either.
embed.mjs targets Node, a browser AND a Worker with nothing but a plain ES
module, so its data has to be plain JS source, not a second import kind.)

Follows grammar_gen.py's and scripts/swift_grammar_gen.py's pattern: a
projection of the source, regenerated and diffed by `--check`, which
test_js_grammar_data.py runs so a stale copy fails the suites. Unlike Swift's
raw multi-line string literals, this needs no length/hash check on the
embedded text: a JS template literal holds real newlines verbatim (no
CRLF-to-LF normalisation the way Swift's multi-line literal has -- refused
below if a source file ever contained a carriage return, so that risk cannot
appear silently), and the only two characters it must escape -- a backslash so
it stays literal, and a backtick or `${` so it does not end the literal or
start an interpolation -- are escaped textually here rather than left for a
lossy re-serialisation of the parsed JSON to reintroduce (grammar/core.json's
own hand-formatted arrays would not round-trip through `json.dumps`
unchanged).
"""
import difflib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_REL = "js/embedded_grammar_data.mjs"
OUT_PATH = os.path.join(REPO, OUT_REL)

# Every file js/loader_node.mjs's loadGrammar() reads, in its order, with the
# name each is embedded under.
SOURCES = (
    ("vocabulary", "grammar/vocabulary.json"),
    ("amber", "grammar/messages/amber.json"),
    ("core", "grammar/core.json"),
)


class EmbedError(Exception):
    pass


def _template_literal(rel: str, text: str) -> str:
    """A JS template literal holding `text` verbatim. Escapes backslash,
    backtick and `${` -- the only sequences a template literal treats
    specially -- in that order, so escaping one never re-triggers another."""
    for ch in text:
        if ch == "\r":
            raise EmbedError(f"{rel} contains a carriage return; a JS template "
                             f"literal normalises that to a line feed, so it "
                             f"would not hold the file verbatim")
        if ord(ch) < 0x20 and ch not in "\n\t":
            raise EmbedError(f"{rel} contains control character U+{ord(ch):04X}, "
                             f"unexpected in grammar data")
    escaped = text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f"`{escaped}`"


def generate() -> str:
    parts = [
        "// GENERATED by scripts/js_grammar_gen.py — do not hand-edit.\n",
        "//\n",
        "// grammar/vocabulary.json, grammar/messages/amber.json and\n",
        "// grammar/core.json, embedded verbatim as JSON text and parsed once here.\n",
        "// The same three files js/loader_node.mjs reads with `fs`, for a host that\n",
        "// cannot read a file (a browser tab, a Cloudflare Worker) or does not carry\n",
        "// this repo. js/embed.mjs loads these into js/grammar_data.mjs; importing\n",
        "// this module alone has no side effect.\n",
        "// Regenerate with `python3 scripts/js_grammar_gen.py`; `--check` (run by\n",
        "// test_js_grammar_data.py) fails when this file is stale.\n",
        "\n",
    ]
    for name, rel in SOURCES:
        with open(os.path.join(REPO, rel), encoding="utf-8", newline="") as f:
            text = f.read()
        parts.append(f"// {rel}\n")
        parts.append(f"export const {name} = JSON.parse({_template_literal(rel, text)});\n")
        parts.append("\n")
    return "".join(parts)


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        generated = generate()
    except EmbedError as e:
        print(f"js_grammar_gen: {e}")
        return 2
    if not check:
        os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
        with open(OUT_PATH, "w", encoding="utf-8", newline="") as f:
            f.write(generated)
        print(f"wrote {OUT_REL} ({', '.join(rel for _, rel in SOURCES)})")
        return 0
    existing = None
    if os.path.exists(OUT_PATH):
        with open(OUT_PATH, encoding="utf-8", newline="") as f:
            existing = f.read()
    if existing == generated:
        print(f"{OUT_REL}: up to date")
        return 0
    print(f"{OUT_REL}: OUT OF DATE — regenerate with python3 scripts/js_grammar_gen.py")
    sys.stdout.writelines(difflib.unified_diff(
        (existing or "").splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=f"{OUT_REL} (committed)", tofile=f"{OUT_REL} (generated)"))
    return 1


if __name__ == "__main__":
    sys.exit(main())
