#!/usr/bin/env python3
"""Embed the grammar's JSON data in the Swift host.

    python3 scripts/swift_grammar_gen.py            write the Swift file
    python3 scripts/swift_grammar_gen.py --check    regenerate into memory, diff
                                                    against the committed file,
                                                    exit non-zero on any difference

js/loader_node.mjs reads grammar/vocabulary.json, grammar/messages/amber.json and
grammar/core.json off disk and injects them into js/grammar_data.mjs. The Swift
library cannot do either: it has to work inside an app that does not carry this
repo, and a SwiftPM resource cannot reach outside swift/. So the same three files
are embedded verbatim, as raw string literals, in
swift/Sources/Planes/Generated/GrammarData.swift, and parsed once at first use.

Embedded is a copy, and a copy goes stale silently -- so this generator follows
grammar_gen.py's pattern: a projection of the source, regenerated and diffed by
`--check`, which test_swift_grammar_data.py runs so a stale copy fails the suites.
Each embedded file also carries its UTF-8 length and FNV-1a 64 hash, which the
Swift side checks before parsing: a literal Swift read differently from the bytes
on disk (a line ending normalised, an escape interpreted) refuses rather than
running on a grammar that is not the one in grammar/.
"""
import difflib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_REL = "swift/Sources/Planes/Generated/GrammarData.swift"
OUT_PATH = os.path.join(REPO, OUT_REL)

# Every file js/loader_node.mjs's loadGrammar() reads, in its order, with the
# Swift name each is embedded under.
SOURCES = (
    ("vocabulary", "grammar/vocabulary.json"),
    ("amber", "grammar/messages/amber.json"),
    ("core", "grammar/core.json"),
)


class EmbedError(Exception):
    pass


def fnv1a64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def _hashes_needed(text: str) -> int:
    """The fewest `#` that make a multi-line raw literal hold `text` verbatim:
    no `"` or `\\` followed by that many `#` may occur in it (the first would
    close the literal, the second would start an escape)."""
    n = 1
    while ('"' + "#" * n) in text or ("\\" + "#" * n) in text:
        n += 1
    return n


def _literal(rel: str, text: str) -> str:
    for ch in text:
        if ch == "\r":
            # Swift normalises a multi-line literal's line endings to \n.
            raise EmbedError(f"{rel} contains a carriage return; a Swift multi-line "
                             f"literal would not hold it verbatim")
        if ord(ch) < 0x20 and ch not in "\n\t" or ord(ch) == 0x7F:
            raise EmbedError(f"{rel} contains control character U+{ord(ch):04X}, "
                             f"which Swift does not accept in a string literal")
    hashes = "#" * _hashes_needed(text)
    return f'{hashes}"""\n{text}\n"""{hashes}'


def generate() -> str:
    parts = [
        "// GENERATED by scripts/swift_grammar_gen.py — do not hand-edit.\n",
        "//\n",
        "// The grammar's JSON data, embedded verbatim: the files js/loader_node.mjs\n",
        "// reads off disk, carried inside the library so it works without this repo.\n",
        "// Regenerate with `python3 scripts/swift_grammar_gen.py`; `--check` (run by\n",
        "// test_swift_grammar_data.py) fails when this file is stale. Grammar.swift\n",
        "// checks each text's length and hash, then parses it once at first use.\n",
        "\n",
        "enum EmbeddedGrammar {\n",
    ]
    for name, rel in SOURCES:
        with open(os.path.join(REPO, rel), "rb") as f:
            data = f.read()
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as e:
            raise EmbedError(f"{rel} is not valid UTF-8 ({e})") from e
        parts.append(
            f"    static let {name} = EmbeddedGrammarFile(\n"
            f'        path: "{rel}",\n'
            f"        utf8Count: {len(data)},\n"
            f"        fnv1a64: 0x{fnv1a64(data):016X},\n"
            f"        text: {_literal(rel, text)}\n"
            f"    )\n")
    parts.append("}\n")
    return "".join(parts)


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        generated = generate()
    except EmbedError as e:
        print(f"swift_grammar_gen: {e}")
        return 2
    if not check:
        os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
        with open(OUT_PATH, "w", encoding="utf-8", newline="") as f:
            f.write(generated)
        print(f"wrote {OUT_REL} ({', '.join(rel for _, rel in SOURCES)})")
        return 0
    existing = None
    if os.path.exists(OUT_PATH):
        with open(OUT_PATH, encoding="utf-8", newline="") as f:
            existing = f.read()
    if existing == generated:
        print(f"{OUT_REL}: up to date")
        return 0
    print(f"{OUT_REL}: OUT OF DATE — regenerate with python3 scripts/swift_grammar_gen.py")
    sys.stdout.writelines(difflib.unified_diff(
        (existing or "").splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=f"{OUT_REL} (committed)", tofile=f"{OUT_REL} (generated)"))
    return 1


if __name__ == "__main__":
    sys.exit(main())
